version: '2'

services:
  pg-master:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis-master:
    image: redis:2.8
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local
